import Head from 'next/head';
import Menu from '../Navigation/Menu';
import { Container } from '@mui/material';

const Layout = ({ children }) => (
  <div>
    <Head>
      <title>NextJS - Expenses</title>
      <meta name="NextJS Project" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Container disableGutters>
      <div>{children}</div>
      <Menu />
    </Container>
  </div>
);

export default Layout;
