import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => (
  <div className={styles.container}>
    <Head>
      <title>NextJS - Expenses</title>
      <meta name="NextJS Project" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <div>Test</div>
    </main>
  </div>
);

export default Home;
